# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78bf25243a9722ac5119ef7b0dff48b2912e630a1afa0da2423852e9024d74c96be7eefb0f4c8e46e02db659feb4d9f71591891637add7b5f1be010b1c94b90

test:
  secret_key_base: e998c28f47f1db26e22cd40bf88a36e1f449fdd0beea5350ec8fa196f0354163be258f5f7a96ce26826676c5285e7d7063e989ce1813c432c3a6e67ac3f3ae90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
